version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: burger-mongodb-1
    ports:
      - "27017:27017"

  fastapi:
    build: .
    ports:
      - "7000:8000"
    depends_on:
      - mongodb
  
  populate_db:
    build: . 
    command: python populate_db/populate_db.py 
    depends_on:
      - mongodb
volumes:
  mongodb_data: